### ISSUE TITLE
HDMI to Optical not working?

### ISSUE THREAD

**Issue by edglazer** [markamccorkle/silentbutdeadly#3]
Might be outside the scope of the project, but I thought I'd inquire. I have an HDMI out from my macbook air, running into my hdtv, and the optical out from the tv runs into my stereo... It's still causing the initial delay which I was hoping this incredibly useful little app would fix. 

Is it possible to fix this using this app?

**Comment by alexandreblin** [comment]
It should work because it plays a constant "silent" sound file so the sound output always stays on.

Did you try restarting the app _after_ plugging the MacBook to the TV to see if it makes any difference?

**Comment by edglazer** [comment]
I checked again after disconnecting/reconnecting (I believe I started the app _before_ I connected to the HDMI) and it seemed like it was working correctly, so I'm going to close the ticket. Thanks again!
